export const howieYears = [
  {
    year: 2026,
    tag: "Year 17 as GM",
    draftGrade: "INC",
    faGrade: "B+",
    draftNote: "Too early to carve in stone. Traded up for Lemon, then loaded the trenches and a Mackey Award tight end.",
    faNote: "Depth and speed after the A.J. Brown trade rumor mill. Greenard via draft-weekend trade is the headline addition.",
    picks: [
      { rnd: "1 / 20", name: "Makai Lemon", pos: "WR", school: "USC", grade: "A-" },
      { rnd: "2 / 54", name: "Eli Stowers", pos: "TE", school: "Vanderbilt", grade: "B+" },
      { rnd: "3 / 68", name: "Markel Bell", pos: "OT", school: "Miami", grade: "B+" },
      { rnd: "5 / 178", name: "Cole Payton", pos: "QB", school: "NDSU", grade: "B" },
      { rnd: "6 / 207", name: "Micah Morris", pos: "G", school: "Georgia", grade: "B" },
      { rnd: "7 / 244", name: "Cole Wisniewski", pos: "S", school: "Texas Tech", grade: "C+" },
      { rnd: "7 / 251", name: "Uar Bernard", pos: "DT", school: "IPP / Nigeria", grade: "INC" },
      { rnd: "7 / 252", name: "Keyshawn James-Newby", pos: "EDGE", school: "New Mexico", grade: "B-" },
    ],
    fas: [
      { name: "Jonathan Greenard", how: "Trade · EDGE", grade: "A-" },
      { name: "Hollywood Brown", how: "1-year · WR", grade: "B+" },
      { name: "Dontayvion Wicks", how: "Trade · WR", grade: "B" },
      { name: "Arnold Ebiketie", how: "1-year · EDGE", grade: "B" },
      { name: "Riq Woolen", how: "1-year · CB", grade: "B" },
      { name: "Elijah Moore", how: "1-year · WR", grade: "C+" },
    ],
  },
  {
    year: 2025,
    tag: "Defending champs",
    draftGrade: "B-",
    faGrade: "B",
    draftNote: "Too soon for a monument, not too soon for a lean. Campbell and Mukuba have to hit for this to climb.",
    faNote: "Paid the Super Bowl core (Baun) more than they hunted new names.",
    picks: [
      { rnd: "1 / 31", name: "Jihaad Campbell", pos: "LB", school: "Alabama", grade: "B" },
      { rnd: "2 / 64", name: "Andrew Mukuba", pos: "S", school: "Texas", grade: "B" },
      { rnd: "4 / 111", name: "Ty Robinson", pos: "DT", school: "Nebraska", grade: "C+" },
      { rnd: "5 / 145", name: "Mac McWilliams", pos: "CB", school: "UCF", grade: "C+" },
      { rnd: "5 / 161", name: "Smael Mondon", pos: "LB", school: "Georgia", grade: "C+" },
      { rnd: "5 / 168", name: "Drew Kendall", pos: "C", school: "Boston College", grade: "B-" },
      { rnd: "6 / 181", name: "Kyle McCord", pos: "QB", school: "Syracuse", grade: "C" },
      { rnd: "6 / 191", name: "Myles Hinton", pos: "OT", school: "Michigan", grade: "C+" },
      { rnd: "6 / 207", name: "Cameron Williams", pos: "OT", school: "Texas", grade: "C+" },
      { rnd: "6 / 209", name: "Antwaun Powell-Ryland", pos: "EDGE", school: "Virginia Tech", grade: "C" },
    ],
    fas: [
      { name: "Zack Baun", how: "Extension · LB", grade: "A" },
      { name: "Core keepers", how: "SB LIX roster", grade: "B+" },
    ],
  },
  {
    year: 2024,
    tag: "The LIX machine",
    draftGrade: "A",
    faGrade: "A+",
    draftNote: "Mitchell and DeJean are already All-Pros. Hunt is growing into money. Best recent haul.",
    faNote: "Saquon and Baun on one-year-then-legend deals. This is the class that ended a dynasty.",
    picks: [
      { rnd: "1 / 22", name: "Quinyon Mitchell", pos: "CB", school: "Toledo", grade: "A+" },
      { rnd: "2 / 40", name: "Cooper DeJean", pos: "DB", school: "Iowa", grade: "A+" },
      { rnd: "3 / 94", name: "Jalyx Hunt", pos: "EDGE", school: "Houston Christian", grade: "B+" },
      { rnd: "4 / 127", name: "Will Shipley", pos: "RB", school: "Clemson", grade: "B-" },
      { rnd: "5 / 152", name: "Ainias Smith", pos: "WR", school: "Texas A&M", grade: "C" },
      { rnd: "5 / 155", name: "Jeremiah Trotter Jr.", pos: "LB", school: "Clemson", grade: "B-" },
      { rnd: "5 / 172", name: "Trevor Keegan", pos: "OL", school: "Michigan", grade: "C+" },
      { rnd: "6 / 185", name: "Johnny Wilson", pos: "WR", school: "Florida State", grade: "C" },
      { rnd: "6 / 190", name: "Dylan McMahon", pos: "C", school: "NC State", grade: "C" },
    ],
    fas: [
      { name: "Saquon Barkley", how: "3 years · RB", grade: "A+" },
      { name: "Zack Baun", how: "1-year · LB", grade: "A+" },
      { name: "C.J. Gardner-Johnson", how: "Return · S", grade: "A-" },
      { name: "Bryce Huff", how: "EDGE", grade: "F" },
    ],
  },
  {
    year: 2023,
    tag: "Carter at 9",
    draftGrade: "B",
    faGrade: "B",
    draftNote: "Carter is a wrecking ball. Ojomo bloomed in 2025. Nolan is a rotational rusher who matters in January.",
    faNote: "Swift and Byard were useful, not immortal.",
    picks: [
      { rnd: "1 / 9", name: "Jalen Carter", pos: "DT", school: "Georgia", grade: "A" },
      { rnd: "1 / 30", name: "Nolan Smith", pos: "EDGE", school: "Georgia", grade: "B" },
      { rnd: "3 / 65", name: "Tyler Steen", pos: "G", school: "Alabama", grade: "C+" },
      { rnd: "3 / 66", name: "Sydney Brown", pos: "S", school: "Illinois", grade: "C+" },
      { rnd: "4 / 105", name: "Kelee Ringo", pos: "CB", school: "Georgia", grade: "C" },
      { rnd: "6 / 188", name: "Tanner McKee", pos: "QB", school: "Stanford", grade: "B" },
      { rnd: "7 / 249", name: "Moro Ojomo", pos: "DT", school: "Texas", grade: "B+" },
    ],
    fas: [
      { name: "D'Andre Swift", how: "RB", grade: "B" },
      { name: "Kevin Byard", how: "S", grade: "B" },
      { name: "Marcus Mariota", how: "QB", grade: "B-" },
    ],
  },
  {
    year: 2022,
    tag: "The Brown trade tree",
    draftGrade: "B+",
    faGrade: "A+",
    draftNote: "Davis, Jurgens, Dean. And the draft also delivered A.J. Brown via trade. That counts in this shrine.",
    faNote: "Reddick, Bradberry, Gardner-Johnson. The 2022 defense was a Howie opera.",
    picks: [
      { rnd: "1 / 13", name: "Jordan Davis", pos: "DT", school: "Georgia", grade: "B+" },
      { rnd: "2 / 51", name: "Cam Jurgens", pos: "C", school: "Nebraska", grade: "B+" },
      { rnd: "3 / 83", name: "Nakobe Dean", pos: "LB", school: "Georgia", grade: "B" },
      { rnd: "6 / 181", name: "Kyron Johnson", pos: "LB", school: "Kansas", grade: "D" },
      { rnd: "6 / 198", name: "Grant Calcaterra", pos: "TE", school: "SMU", grade: "B" },
    ],
    fas: [
      { name: "A.J. Brown", how: "Trade · WR", grade: "A+" },
      { name: "Haason Reddick", how: "EDGE", grade: "A" },
      { name: "James Bradberry", how: "CB", grade: "A" },
      { name: "C.J. Gardner-Johnson", how: "S", grade: "A" },
    ],
  },
  {
    year: 2021,
    tag: "Smith and the line",
    draftGrade: "A-",
    faGrade: "C",
    draftNote: "DeVonta. Dickerson. Milton Williams, who cashed out after LIX. Gainwell in the fifth.",
    faNote: "Bridge veterans. The draft did the lifting.",
    picks: [
      { rnd: "1 / 10", name: "DeVonta Smith", pos: "WR", school: "Alabama", grade: "A" },
      { rnd: "2 / 37", name: "Landon Dickerson", pos: "G", school: "Alabama", grade: "A" },
      { rnd: "3 / 73", name: "Milton Williams", pos: "DT", school: "Louisiana Tech", grade: "A-" },
      { rnd: "4 / 123", name: "Zech McPhearson", pos: "CB", school: "Texas Tech", grade: "D" },
      { rnd: "5 / 150", name: "Kenneth Gainwell", pos: "RB", school: "Memphis", grade: "B" },
      { rnd: "6 / 189", name: "Marlon Tuipulotu", pos: "DT", school: "USC", grade: "C" },
      { rnd: "6 / 191", name: "Tarron Jackson", pos: "EDGE", school: "Coastal Carolina", grade: "C-" },
      { rnd: "6 / 224", name: "JaCoby Stevens", pos: "S", school: "LSU", grade: "F" },
      { rnd: "7 / 234", name: "Patrick Johnson", pos: "EDGE", school: "Tulane", grade: "C" },
    ],
    fas: [
      { name: "Joe Flacco", how: "QB", grade: "C" },
      { name: "Ryan Kerrigan", how: "EDGE", grade: "C" },
    ],
  },
  {
    year: 2020,
    tag: "Two Jalens",
    draftGrade: "B-",
    faGrade: "B+",
    draftNote: "Hurts in the second is a franchise. Reagor at 21 is the ghost Howie still hears.",
    faNote: "Slay via trade. Hargrave in the middle. Real pieces around a messy draft.",
    picks: [
      { rnd: "1 / 21", name: "Jalen Reagor", pos: "WR", school: "TCU", grade: "F" },
      { rnd: "2 / 53", name: "Jalen Hurts", pos: "QB", school: "Oklahoma", grade: "A+" },
      { rnd: "3 / 103", name: "Davion Taylor", pos: "LB", school: "Colorado", grade: "D" },
      { rnd: "4 / 127", name: "K'Von Wallace", pos: "S", school: "Clemson", grade: "C-" },
      { rnd: "4 / 145", name: "Jack Driscoll", pos: "OL", school: "Auburn", grade: "C+" },
      { rnd: "5 / 168", name: "John Hightower", pos: "WR", school: "Boise State", grade: "F" },
      { rnd: "6 / 196", name: "Shaun Bradley", pos: "LB", school: "Temple", grade: "C" },
      { rnd: "6 / 200", name: "Quez Watkins", pos: "WR", school: "USF", grade: "C+" },
      { rnd: "6 / 210", name: "Prince Tega Wanogho", pos: "OT", school: "Auburn", grade: "D" },
      { rnd: "7 / 233", name: "Casey Toohill", pos: "EDGE", school: "Stanford", grade: "C+" },
    ],
    fas: [
      { name: "Darius Slay", how: "Trade · CB", grade: "A" },
      { name: "Javon Hargrave", how: "DT", grade: "A-" },
    ],
  },
  {
    year: 2019,
    tag: "The Dillard winter",
    draftGrade: "D+",
    faGrade: "C",
    draftNote: "Dillard over Tytus Howard. JJAW over DK. Sanders was fine. The rest is trivia.",
    faNote: "Stopgaps after a Super Bowl hangover.",
    picks: [
      { rnd: "1 / 22", name: "Andre Dillard", pos: "OT", school: "Washington State", grade: "D" },
      { rnd: "2 / 53", name: "Miles Sanders", pos: "RB", school: "Penn State", grade: "B" },
      { rnd: "2 / 57", name: "JJ Arcega-Whiteside", pos: "WR", school: "Stanford", grade: "F" },
      { rnd: "4 / 138", name: "Shareef Miller", pos: "EDGE", school: "Penn State", grade: "F" },
      { rnd: "5 / 167", name: "Clayton Thorson", pos: "QB", school: "Northwestern", grade: "F" },
    ],
    fas: [
      { name: "Jordan Howard", how: "RB", grade: "C+" },
      { name: "Vinny Curry", how: "Return · EDGE", grade: "C" },
    ],
  },
  {
    year: 2018,
    tag: "Best Howie haul",
    draftGrade: "A+",
    faGrade: "C+",
    draftNote: "Traded out of R1. Goedert, Maddox, Sweat, Mailata in the seventh. Efficiency as religion.",
    faNote: "Michael Bennett and Mike Wallace were not the point. The draft was.",
    picks: [
      { rnd: "2 / 49", name: "Dallas Goedert", pos: "TE", school: "South Dakota State", grade: "A" },
      { rnd: "4 / 125", name: "Avonte Maddox", pos: "CB", school: "Pittsburgh", grade: "B+" },
      { rnd: "4 / 130", name: "Josh Sweat", pos: "EDGE", school: "Florida State", grade: "A" },
      { rnd: "6 / 206", name: "Matt Pryor", pos: "OL", school: "TCU", grade: "C" },
      { rnd: "7 / 233", name: "Jordan Mailata", pos: "OT", school: "Rugby / Australia", grade: "A+" },
    ],
    fas: [
      { name: "Michael Bennett", how: "EDGE", grade: "C" },
      { name: "Mike Wallace", how: "WR", grade: "C-" },
    ],
  },
  {
    year: 2017,
    tag: "LII pieces, not LII draft",
    draftGrade: "C",
    faGrade: "A",
    draftNote: "Barnett recovered the fumble. Watt was on the board. Douglas and Hollins bloomed elsewhere.",
    faNote: "Alshon, Long, Robinson, Torrey, Foles. The Super Bowl was signed in March.",
    picks: [
      { rnd: "1 / 14", name: "Derek Barnett", pos: "EDGE", school: "Tennessee", grade: "C+" },
      { rnd: "2 / 43", name: "Sidney Jones", pos: "CB", school: "Washington", grade: "C-" },
      { rnd: "3 / 99", name: "Rasul Douglas", pos: "CB", school: "West Virginia", grade: "B-" },
      { rnd: "4 / 118", name: "Mack Hollins", pos: "WR", school: "North Carolina", grade: "B-" },
      { rnd: "4 / 132", name: "Donnel Pumphrey", pos: "RB", school: "San Diego State", grade: "F" },
      { rnd: "5 / 166", name: "Shelton Gibson", pos: "WR", school: "West Virginia", grade: "F" },
      { rnd: "5 / 184", name: "Nate Gerry", pos: "LB", school: "Nebraska", grade: "C" },
      { rnd: "6 / 214", name: "Elijah Qualls", pos: "DT", school: "Washington", grade: "D" },
    ],
    fas: [
      { name: "Alshon Jeffery", how: "WR", grade: "A" },
      { name: "Chris Long", how: "EDGE", grade: "A" },
      { name: "Patrick Robinson", how: "CB", grade: "A" },
      { name: "Torrey Smith", how: "WR", grade: "B+" },
      { name: "Nick Foles", how: "Re-signed · QB", grade: "A+" },
    ],
  },
  {
    year: 2016,
    tag: "Back in power",
    draftGrade: "B+",
    faGrade: "B+",
    draftNote: "Wentz at 2. The later trade tree helped grow Smith, Brown, Carter, DeJean. Mills in the seventh.",
    faNote: "Brooks and Bradham were the line and the green-dot.",
    picks: [
      { rnd: "1 / 2", name: "Carson Wentz", pos: "QB", school: "NDSU", grade: "B" },
      { rnd: "3 / 79", name: "Isaac Seumalo", pos: "OL", school: "Oregon State", grade: "B+" },
      { rnd: "5 / 153", name: "Wendell Smallwood", pos: "RB", school: "West Virginia", grade: "C" },
      { rnd: "5 / 164", name: "Halapoulivaati Vaitai", pos: "OT", school: "TCU", grade: "B" },
      { rnd: "6 / 196", name: "Blake Countess", pos: "DB", school: "Auburn", grade: "C-" },
      { rnd: "7 / 233", name: "Jalen Mills", pos: "S", school: "LSU", grade: "B+" },
      { rnd: "7 / 240", name: "Alex McCalister", pos: "EDGE", school: "Florida", grade: "F" },
      { rnd: "7 / 251", name: "Joe Walker", pos: "LB", school: "Oregon", grade: "C" },
    ],
    fas: [
      { name: "Brandon Brooks", how: "G", grade: "A" },
      { name: "Nigel Bradham", how: "LB", grade: "B+" },
    ],
  },
  {
    year: 2015,
    tag: "Chip had the stick",
    chip: true,
    draftGrade: "C",
    faGrade: "F",
    draftNote: "Kelly's draft. Agholor was better than the memes. Hicks was a player. Still not Howie's room.",
    faNote: "Bradford, Maxwell, Murray. The bill for 2015 still echoes.",
    picks: [
      { rnd: "1 / 20", name: "Nelson Agholor", pos: "WR", school: "USC", grade: "C+" },
      { rnd: "2 / 47", name: "Eric Rowe", pos: "CB", school: "Utah", grade: "C" },
      { rnd: "3 / 84", name: "Jordan Hicks", pos: "LB", school: "Texas", grade: "B" },
      { rnd: "6 / 191", name: "JaCorey Shepherd", pos: "CB", school: "Kansas", grade: "D" },
      { rnd: "6 / 196", name: "Randall Evans", pos: "CB", school: "Kansas State", grade: "D" },
      { rnd: "7 / 237", name: "Brian Mihalik", pos: "DE", school: "Boston College", grade: "F" },
    ],
    fas: [
      { name: "DeMarco Murray", how: "RB", grade: "F" },
      { name: "Byron Maxwell", how: "CB", grade: "F" },
      { name: "Sam Bradford", how: "Trade · QB", grade: "D" },
    ],
  },
  {
    year: 2014,
    tag: "Marcus Smith winter",
    draftGrade: "D",
    faGrade: "A-",
    draftNote: "Smith over DeMarcus Lawrence. Matthews over Davante Adams. Beau Allen was a nose.",
    faNote: "Malcolm Jenkins. Darren Sproles. This FA class still pays rent in the trophy case.",
    picks: [
      { rnd: "1 / 26", name: "Marcus Smith", pos: "EDGE", school: "Louisville", grade: "F" },
      { rnd: "2 / 42", name: "Jordan Matthews", pos: "WR", school: "Vanderbilt", grade: "C+" },
      { rnd: "3 / 86", name: "Josh Huff", pos: "WR", school: "Oregon", grade: "D" },
      { rnd: "4 / 101", name: "Jaylen Watkins", pos: "DB", school: "Florida", grade: "C-" },
      { rnd: "5 / 141", name: "Taylor Hart", pos: "DE", school: "Oregon", grade: "D" },
      { rnd: "5 / 162", name: "Ed Reynolds", pos: "S", school: "Stanford", grade: "D" },
      { rnd: "7 / 224", name: "Beau Allen", pos: "DT", school: "Wisconsin", grade: "C+" },
    ],
    fas: [
      { name: "Malcolm Jenkins", how: "S", grade: "A+" },
      { name: "Darren Sproles", how: "RB", grade: "A" },
      { name: "Mark Sanchez", how: "QB", grade: "B" },
    ],
  },
  {
    year: 2013,
    tag: "Lane and Ertz",
    draftGrade: "A+",
    faGrade: "B+",
    draftNote: "Johnson at 4. Ertz at 35. Logan. Poyer became an All-Pro somewhere else. Ace at the top.",
    faNote: "Barwin on the edge. Kelly's first year, Howie still in the room.",
    picks: [
      { rnd: "1 / 4", name: "Lane Johnson", pos: "OT", school: "Oklahoma", grade: "A+" },
      { rnd: "2 / 35", name: "Zach Ertz", pos: "TE", school: "Stanford", grade: "A" },
      { rnd: "3 / 67", name: "Bennie Logan", pos: "DT", school: "LSU", grade: "B" },
      { rnd: "4 / 98", name: "Matt Barkley", pos: "QB", school: "USC", grade: "D" },
      { rnd: "5 / 136", name: "Earl Wolff", pos: "S", school: "NC State", grade: "D" },
      { rnd: "7 / 212", name: "Joe Kruger", pos: "DE", school: "Utah", grade: "F" },
      { rnd: "7 / 218", name: "Jordan Poyer", pos: "S", school: "Oregon State", grade: "B-" },
      { rnd: "7 / 239", name: "David King", pos: "DT", school: "Oklahoma", grade: "D" },
    ],
    fas: [
      { name: "Connor Barwin", how: "EDGE", grade: "A-" },
      { name: "Bradley Fletcher", how: "CB", grade: "C" },
    ],
  },
  {
    year: 2012,
    tag: "Cox, then Foles",
    draftGrade: "A",
    faGrade: "B",
    draftNote: "Cox is a Mount Rushmore pick. Kendricks, Curry, Foles. Super Bowl DNA.",
    faNote: "DeMeco Ryans taught the defense how to be serious.",
    picks: [
      { rnd: "1 / 12", name: "Fletcher Cox", pos: "DT", school: "Mississippi State", grade: "A+" },
      { rnd: "2 / 46", name: "Mychal Kendricks", pos: "LB", school: "California", grade: "B+" },
      { rnd: "2 / 59", name: "Vinny Curry", pos: "EDGE", school: "Marshall", grade: "B" },
      { rnd: "3 / 88", name: "Nick Foles", pos: "QB", school: "Arizona", grade: "A" },
      { rnd: "4 / 123", name: "Brandon Boykin", pos: "CB", school: "Georgia", grade: "B-" },
      { rnd: "5 / 153", name: "Dennis Kelly", pos: "OT", school: "Purdue", grade: "C+" },
      { rnd: "6 / 194", name: "Marvin McNutt", pos: "WR", school: "Iowa", grade: "F" },
      { rnd: "6 / 200", name: "Brandon Washington", pos: "OL", school: "Miami", grade: "D" },
      { rnd: "7 / 229", name: "Bryce Brown", pos: "RB", school: "Kansas State", grade: "C" },
    ],
    fas: [
      { name: "DeMeco Ryans", how: "LB", grade: "A-" },
      { name: "Evan Mathis", how: "Already here · G", grade: "A" },
    ],
  },
  {
    year: 2011,
    tag: "The fireman, then Kelce",
    draftGrade: "C+",
    faGrade: "D",
    draftNote: "Watkins was a miss. Sixth-round Jason Kelce is a civic holiday.",
    faNote: "The Dream Team. Asomugha, Young, name-brand wreckage.",
    picks: [
      { rnd: "1 / 23", name: "Danny Watkins", pos: "G", school: "Baylor", grade: "F" },
      { rnd: "2 / 54", name: "Jaiquawn Jarrett", pos: "S", school: "Temple", grade: "F" },
      { rnd: "3 / 90", name: "Curtis Marsh", pos: "CB", school: "Utah State", grade: "D" },
      { rnd: "4 / 116", name: "Casey Matthews", pos: "LB", school: "Oregon", grade: "C-" },
      { rnd: "4 / 120", name: "Alex Henery", pos: "K", school: "Nebraska", grade: "C-" },
      { rnd: "5 / 149", name: "Dion Lewis", pos: "RB", school: "Pittsburgh", grade: "B-" },
      { rnd: "5 / 161", name: "Julian Vandervelde", pos: "OL", school: "Iowa", grade: "C" },
      { rnd: "6 / 191", name: "Jason Kelce", pos: "C", school: "Cincinnati", grade: "A+" },
      { rnd: "6 / 193", name: "Brian Rolle", pos: "LB", school: "Ohio State", grade: "C" },
      { rnd: "7 / 237", name: "Greg Lloyd", pos: "LB", school: "Connecticut", grade: "F" },
      { rnd: "7 / 240", name: "Stanley Havili", pos: "FB", school: "USC", grade: "C" },
    ],
    fas: [
      { name: "Nnamdi Asomugha", how: "CB", grade: "D" },
      { name: "Vince Young", how: "QB", grade: "D" },
      { name: "Cullen Jenkins", how: "DT", grade: "B" },
      { name: "Ronnie Brown", how: "RB", grade: "C" },
    ],
  },
  {
    year: 2010,
    tag: "First pick: Graham",
    draftGrade: "B-",
    faGrade: "C",
    draftNote: "Moved up for Brandon Graham. Bookended later by Kurt Coleman. The middle is expert trivia.",
    faNote: "Young roster, modest shopping. The draft was the statement.",
    picks: [
      { rnd: "1 / 13", name: "Brandon Graham", pos: "EDGE", school: "Michigan", grade: "A+" },
      { rnd: "2 / 37", name: "Nate Allen", pos: "S", school: "South Florida", grade: "C+" },
      { rnd: "3 / 86", name: "Daniel Te'o-Nesheim", pos: "DE", school: "Washington", grade: "D" },
      { rnd: "4 / 105", name: "Trevard Lindley", pos: "CB", school: "Kentucky", grade: "D" },
      { rnd: "4 / 121", name: "Keenan Clayton", pos: "LB", school: "Oklahoma", grade: "D" },
      { rnd: "4 / 122", name: "Mike Kafka", pos: "QB", school: "Northwestern", grade: "C-" },
      { rnd: "4 / 125", name: "Clay Harbor", pos: "TE", school: "Missouri State", grade: "C" },
      { rnd: "5 / 134", name: "Ricky Sapp", pos: "DE", school: "Clemson", grade: "F" },
      { rnd: "5 / 159", name: "Riley Cooper", pos: "WR", school: "Florida", grade: "C+" },
      { rnd: "6 / 200", name: "Charles Scott", pos: "RB", school: "LSU", grade: "F" },
      { rnd: "7 / 220", name: "Jamar Chaney", pos: "LB", school: "Mississippi State", grade: "C" },
      { rnd: "7 / 243", name: "Jeff Owens", pos: "DT", school: "Georgia", grade: "F" },
      { rnd: "7 / 244", name: "Kurt Coleman", pos: "S", school: "Ohio State", grade: "B+" },
    ],
    fas: [
      { name: "Youth movement", how: "Cap reset", grade: "C" },
    ],
  },
];
